- name: Install postgresql packages
  apt: name={{item}}
  with_items:
    - postgresql
    - postgresql-contrib
    - python-psycopg2   # Needed for ansible management

- name: Generate and set postgres admin password
  sudo: yes
  sudo_user: postgres
  postgresql_user: name=postgres
    password="{{lookup('password', playbook_dir + '/credentials/passwords/postgresql_admin_password')}}"

