- name: Install nginx
  apt: name=nginx
  notify: restart nginx
- name: Enable nginx service
  service: name=nginx enabled=yes
- name: Upload nginx config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: reload nginx
