- name: Create project user
  user: name="{{user}}" shell="/bin/bash"
- name: Add authorized keys
  authorized_key: 
    key: "{{ item }}"
    user: "{{ user }}"
  with_items: "{{authorized_keys}}"

- name: Generate deploy ssh key
  local_action: command ssh-keygen -P "" -f {{deploy_ssh_key}} creates={{deploy_ssh_key}}
  when: generate_deploy_ssh_key and not deploy_ssh_key_public and not deploy_ssh_key_private
- name: Upload private deploy ssh key
  sudo: yes
  sudo_user: "{{user}}"
  copy: content="{{deploy_ssh_key_private}}"
    dest="~/.ssh/id_rsa"
    owner="{{user}}"
    group="{{user}}"
    mode="0600"
    backup=yes
  when: generate_deploy_ssh_key
- name: Upload public deploy ssh key
  sudo: yes
  sudo_user: "{{user}}"
  copy: content="{{deploy_ssh_key_public}}"
    dest="~/.ssh/id_rsa.pub"
    owner="{{user}}"
    group="{{user}}"
    mode="0600"
    backup=yes
  when: generate_deploy_ssh_key

- name: Create user profile.d dir
  file: path="~/.profile.d/" state=directory
  sudo: yes
  sudo_user: "{{user}}"
- name: Setup bash autosourcing .profile.d
  lineinfile: dest="~/.profile" line="for f in ~/.profile.d/*; do source $f; done"
  sudo: yes
  sudo_user: "{{user}}"

- name: Generate app environment file
  template: src=env.sh.j2 dest=~/.profile.d/project_env.sh
  sudo: yes
  sudo_user: "{{user}}"

# In ansible 1.6 include with_items was deprecated
# Wait for ansible 2.0 release to rewrite this
- include: "postgresql.yml"
  when: '"postgresql" in services'
  tags:
    - db
    - postgres
- include: "passenger.yml"
  when: '"passenger" in services'
  tags:
    - web
    - passenger
- include: "redis.yml"
  when: '"redis" in services'
  tags:
    - cache
    - redis
