- include: swap.yml
  when: swap_file_enable

- name: Install utils
  apt: name={{item}} update_cache=true
  with_items:
    - git
    - rsync
    - sudo

- name: Install systemd
  apt: name={{item}} update_cache=true
  with_items:
    - libpam-systemd

- name: Create journal logs dir
  file: path=/var/log/journal state=directory
