- name: Add Phusion Passenger key
  apt_key: keyserver=keyserver.ubuntu.com id=561F9B9CAC40B2F7
- name: Add Phusion Passenger repository
  apt_repository: repo='deb https://oss-binaries.phusionpassenger.com/apt/passenger trusty main' update_cache=yes
- name: Install nginx with passenger
  apt: name="{{item}}"
  notify: restart nginx
  with_items:
    - nginx-extras
    - passenger
- name: Enable nginx service
  service: name=nginx enabled=yes
- name: Upload nginx config
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: reload nginx
# - name: Delete default nginx site
#   file: path="/etc/nginx/sites-enabled/default" state=absent
#   notify: reload nginx
